import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import 'react-tooltip/dist/react-tooltip.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'Next.js Basic App',
    template: '%s | Next.js Course'
  },
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-blue-100 py-14">
          <div className="container mx-auto px-4">
            <Navbar />
          </div>
        </header>
        <main className="main-container">
          <div className="container mx-auto px-4">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  )
}
